force-app/main/default/objects/SA_Citizen__c/SA_Citizen__c.object-meta.xml
<CustomObject>
    <label>SA Citizen</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>SA Citizen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Citizens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Citizen__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Counter to Count number of Searches</description>
    <inlineHelpText>Counter to Count number of Searches</inlineHelpText>
    <label>Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SA_Citizen__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <description>Assuming the Date of Birth is will be passed by 19 Century.</description>
    <formula>DATEVALUE(&quot;19&quot;&amp;MID(TEXT( SA_Id_Number__c ),1,2)&amp;&quot;-&quot;&amp; MID(TEXT(SA_Id_Number__c),3,2)&amp;&quot;-&quot;&amp; MID(TEXT(SA_Id_Number__c),5,2))</formula>
    <inlineHelpText>Date Of Birth</inlineHelpText>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SA_Citizen__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of the Citizen</description>
    <formula>IF( VALUE(MID(TEXT(SA_Id_Number__c), 7, 4))  &gt;= 5000  , &apos;Male&apos;, &apos;Female&apos;)</formula>
    <inlineHelpText>Gender</inlineHelpText>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Citizen__c/fields/Is_Citizen__c.field-meta.xml
<CustomField>
    <fullName>Is_Citizen__c</fullName>
    <description>To Determine whether the Id user is Citizen or Permanent Resident</description>
    <formula>IF( MID(  TEXT(SA_Id_Number__c), 11, 1)  =  &apos;0&apos; , &apos;SA Citizen&apos;, &apos;Permanent Resident&apos;)</formula>
    <inlineHelpText>SA Citizen or Permanent Resident</inlineHelpText>
    <label>Is Citizen</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Citizen__c/fields/SA_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>SA_Id_Number__c</fullName>
    <description>Stores the Information related to South African Id Number</description>
    <inlineHelpText>South African Id</inlineHelpText>
    <label>SA Id Number</label>
    <precision>13</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SADatabaseHelper.cls
public without sharing class SADatabaseHelper {
    /**
     * @description : To get the Citizen Record Based on the SA Id Number
     * @param idNo IdNumber
     * @return Citizen Record based on the Id passed 
	*/
    public static SA_Citizen__c getCitizenRecordById(Decimal idNo){
        SA_Citizen__c saCitizenRecord = null;
        try{
            List<SA_Citizen__c> lstSaRecord=[Select Id,Name,SA_Id_Number__c,Date_Of_Birth__c
                                             ,Gender__c,Is_Citizen__c,Counter__c from SA_Citizen__c 
                                             where SA_Id_Number__c =:idNo  Limit 1];
            if(lstSaRecord.size() > 0){
                saCitizenRecord=lstSaRecord[0];
            }
        }catch(Exception ex){
            throw ex;
        }
        return saCitizenRecord;
    }
    /**
     * @description : To upsert the record
     * @param saCitizenRecord IdNumber
	*/
    public static void upsertCitizenRecord(SA_Citizen__c saCitizenRecord){
        try{
            //Update Record If Present and Insert if Not
            if(saCitizenRecord !=null){
                upsert saCitizenRecord;
            }            
        }catch(Exception ex){
            throw ex;
        }
    }
}